name: Image-creation-dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKER_VERSION: "1.9.4"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }} 

      - name: packer init
        run: packer init .
        working-directory: ./packer/

      - name: packer validate
        run: packer validate -var-file="dev.pkrvars.hcl" .
        working-directory: ./packer/

      - name: packer formatting
        run: packer fmt .
        working-directory: ./packer/

      - name: building image
        run: packer build -var-file="dev.pkrvars.hcl" .
        working-directory: ./packer/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.DEV_AWS_REGION }}

      - name: Dev deployment starter
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: Aswathy-1717/aswathy
          event-type: dev-deploy-event

